### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by noinarisak**
Update README. GoDoc API Reference URL should default to `v2` version.

## Summary

Fixes #

## Type of PR

- [ ] Bug Fix (non-breaking fixes to existing functionality)
- [ ] New Feature (non-breaking changes that add new functionality)
- [x] Documentation update
- [ ] Test Updates
- [ ] Other (Please describe the type)

## Test Information

- [ ] My PR required test updates 

Go Version: n/a
Os Version: n/a
OpenAPI Spec Version: n/a

## Signoff
- [ ] I have submitted a CLA for this PR
- [ ] Each commit message explains what the commit does
- [ ] I have updated documentation to explain what my PR does
- [ ] My code is covered by tests if required
- [ ] I ran `make fmt` on my code
- [ ] I did not edit any automatically generated files

### CODE REVIEW

**Comment by noinarisak** [comment]
@monde Looking at TravisCI, my build did not have the same Environment Variables compared to https://app.travis-ci.com/github/okta/okta-sdk-golang/jobs/568259660. 

Am I missing something?

**Review by monde — APPROVED** [review]

**Comment by monde** [comment]
> @monde Looking at TravisCI, my build did not have the same Environment Variables compared to https://app.travis-ci.com/github/okta/okta-sdk-golang/jobs/568259660.
> 
> Am I missing something?

CI won't use the private ENV variables on forked repo. I'll make parallel branch and cherry pick that in.

**Comment by monde** [comment]
Closing for #301

**Comment by noinarisak** [comment]
🌮 🎉

**Pull request closed without merging**
