### PR TITLE
Feature update version

### PR DESCRIPTION
**Pull request by halmai**
This PR updates the version number from `2.3.0` to `2.3.1`.

### CODE REVIEW

**Comment by halmai** [comment]
@bretterer Could you help me with managing this travis issue, please? 
We need the new version number in order to refer to it in our go.mod file. 
Thanks.

**Comment by halmai** [comment]
@bretterer Is there any progress with this PR? A very small one but we would need it. Could you approve and merge it, please?

**Comment by halmai** [comment]
@bretterer Is there any progress with this PR? 

I don't really mind if somebody merges the failing PR issue in general, just merges this PR or adds the new version number manually, I just would like to refer to the most recent version in our `go.mod` file. Can you, or anyone help us, please?

**Comment by monde** [comment]
@halmai I'll look into this today.

**Comment by monde** [comment]
Ok @halmai I brought this into master and did v2.3.1 release. Let me know if you are good to go!

**Pull request merged**
