### PR TITLE
Feature/improve oatuh2 servapp doc

### PR DESCRIPTION
**Pull request by juanmatias**
Improved documentation with a more extensive and detailed example on how to connect using OAuth2 Service App.

Two minor fixes to CONTRIBUTING.md file.

### CODE REVIEW

**Comment by juanmatias** [comment]
Despite I just modified two md files and used last code base from upstream/master check is failing with this:

```
Received unexpected error:

        	            	your Okta API token is missing. You can generate one in the Okta Developer Console. Follow these instructions: https://bit.ly/get-okta-api-token
```

Is there an issue in the upstream/master branch? Please give me some advice.

**Comment by bryanapellanes-okta** [comment]
@juanmatias,
Thanks for reaching out!  I'll open an internal issue for our Go developers to review, we will comment here when we have additional information.

Thanks for using Okta!

**Comment by bretterer** [comment]
@juanmatias Thank you for the PR, Because of our Travis-ci integration, it will not run from this PR due to private env variables.

We will work on this shortly to get it merged in. Thank you for your contribution!

**Comment by monde** [comment]
Thank you @juanmatias! I brought your suggestions into a parallel branch and merged it into master. I'll close this PR.

**Pull request closed without merging**
