### PR TITLE
Fix deserialisation of error causes

### PR DESCRIPTION
**Pull request by CedricFinance**

### CODE REVIEW

**Comment by bretterer** [comment]
Hi @CedricFinance  ! Thanks for your pull request.

Before we can move forward with reviewing/merging your PR, please take a moment to read and sign a Contributor License Agreement (CLA).

Please visit developer.okta.com/cla to sign.

Then, reply here (“Signed”) so we can proceed.

We also need all PR's to be made against the develop branch.

Thanks!

**Comment by CedricFinance** [comment]
Signed

**Comment by bretterer** [comment]
Great.  I also need this to be set to base branch develop and rebased.  once that is done, we are good to merge.  Thank you!

**Comment by CedricFinance** [comment]
I've changed the base branch and rebased.

**Comment by bretterer** [comment]
Thank you!

**Pull request merged**
