### PR TITLE
add case for float64 type in query.String()

### LINKED ISSUE #27: query.WithLimit conversion panic
with the following config...

```
package main

import (
	"fmt"
	"github.com/okta/okta-sdk-golang/okta"
        "github.com/okta/okta-sdk-golang/okta/query"
)

func main() {
	config := okta.NewConfig().WithOrgUrl("https://xxxxxxx.oktapreview.com").WithToken("xxxxxxxxxxxxxxxxxxxxxxxxxxxx")
	client := okta.NewClient(config, nil, nil)

        qp := query.NewQueryParams(query.WithLimit(1))

	fmt.Println(qp)

	users, _, _ := client.User.ListUsers(qp)
	
	for _, user := range users {
		resp, _, _ := client.User.GetUser(user.Id, nil)
		profile := resp.Profile
		fmt.Println((*profile)["email"])
	}
}
```

...I get the following error when trying to use `query.WithLimit(1)`...

```
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
github.com/okta/okta-sdk-golang/okta/query.(*Params).String(0xc4200e3440, 0xd, 0x0)
	/Users/spurr/golang/src/github.com/okta/okta-sdk-golang/okta/query/query.go:206 +0x404
github.com/okta/okta-sdk-golang/okta.(*UserResource).ListUsers(0xc4200b3850, 0xc4200e3440, 0x1, 0x45, 0x0, 0x0, 0x0, 0xc42006bf78)
	/Users/spurr/golang/src/github.com/okta/okta-sdk-golang/okta/user.go:115 +0x1f1
main.main()
	/Users/spurr/src/okta-test/main.go:17 +0x151
```

It looks like [this switch block](https://github.com/okta/okta-sdk-golang/blob/master/okta/query/query.go#L202) is in need of an `float64` case to convert it to a string before tacking it onto the query string.

### PR DESCRIPTION
**Pull request by PurrBiscuit**
adding a case in the query.String() switch statement for `float64` type

Fixes #27

### CODE REVIEW

**Comment by paulquerna-okta** [comment]
This needs to be fixed in the template file located at `openapi/generator/templates/query.go.hbs`

**Comment by bretterer** [comment]
Hi @PurrBiscuit ! Thanks for your pull request.

Before we can move forward with reviewing/merging your PR, please take a moment to read and sign a Contributor License Agreement (CLA).

Please visit developer.okta.com/cla to sign.

Then, reply here (“Signed”) so we can proceed. 

We also need all PR's to be made against the develop branch. 

Thanks!

**Comment by PurrBiscuit** [comment]
Signed

**Comment by PurrBiscuit** [comment]
looks like this was already handled on the develop branch so I'm going to close out this PR

**Comment by bretterer** [comment]
Thank you for the PR on this.

**Pull request closed without merging**
