### PR TITLE
Adds ability to specify JWT kid header 

### PR DESCRIPTION
**Pull request by emanor-okta**
## Summary

Adds ability to specify JWT kid header for when Okta service app has more then a single JWK registered.
Okta service applications with more then a single JWK registered will reject /token calls if the JWT assertion does not contain the key id (kid) header.

Fixes #

## Type of PR

- [ ] Bug Fix (non-breaking fixes to existing functionality)
- [X] New Feature (non-breaking changes that add new functionality)
- [X] Documentation update
- [ ] Test Updates
- [ ] Other (Please describe the type)

## Test Information

- [ ] My PR required test updates 

Go Version:
Os Version:
OpenAPI Spec Version:

## Signoff
- [X] I have submitted a CLA for this PR
- [X] Each commit message explains what the commit does
- [X] I have updated documentation to explain what my PR does
- [ ] My code is covered by tests if required
- [ ] I ran `make fmt` on my code
- [X] I did not edit any automatically generated files

### CODE REVIEW

**Comment by emanor-okta** [comment]
remove stale

**Review by monde — APPROVED** [review]

**Comment by monde** [comment]
@emanor-okta CI will only run against PRs off the okta/okta-sdk-golang repo, not forks. I'll have to start branch to bring your commits in.

**Comment by monde** [comment]
@emanor-okta I cherry picked these changes into #308

**Comment by monde** [comment]
This was released in v2.13.0 https://github.com/okta/okta-sdk-golang/releases/tag/v2.13.0

**Pull request closed without merging**
