### PR TITLE
Fixed URL for auth_server_policy_rule

### PR DESCRIPTION
**Pull request by bogdanprodan-okta**

### CODE REVIEW

**Review by monde — APPROVED** [review]

**Comment by mayitbeegh** [comment]
Is this getting merged? I just ran into this very issue in the latest version. @bogdanprodan-okta @monde

**Comment by monde** [comment]
> Is this getting merged? I just ran into this very issue in the latest version. @bogdanprodan-okta @monde

@mayitbeegh I'll see if I can do permanent fix, I'm trying to release v2.12.0 today.

**Comment by mayitbeegh** [comment]
Thank you. Let me know if I can be of any help.

**Comment by monde** [comment]
@mayitbeegh released at v2.12.0 https://github.com/okta/okta-sdk-golang/releases/tag/v2.12.0

Please note the parameters in the method signatures.

- `AuthorizationServerResource`
  - `DeleteAuthorizationServerPolicyRule(ctx context.Context, authServerId string, policyId string, ruleId string)`
  - `GetAuthorizationServerPolicyRule(ctx context.Context, authServerId string, policyId string, ruleId string)`
  - `UpdateAuthorizationServerPolicyRule(ctx context.Context, authServerId string, policyId string, ruleId string, body AuthorizationServerPolicyRule)`
- `AuthorizationServerPolicyRuleResource`
  - `UpdateAuthorizationServerPolicyRule(ctx context.Context, authServerId string, policyId string, ruleId string, body AuthorizationServerPolicyRule)`
  - `DeleteAuthorizationServerPolicyRule(ctx context.Context, authServerId string, policyId string, ruleId string)`

**Comment by monde** [comment]
Ugh, @mayitbeegh I didn't catch issues with a couple of other endpoints. Look for a v2.12.1 release on Monday+

see:
https://github.com/okta/okta-management-openapi-spec/pull/131
https://github.com/okta/okta-sdk-golang/pull/291

- `AuthorizationServerResource`
  - `ListAuthorizationServerPolicyRules(ctx context.Context, authServerId string, policyId string)`
  - `CreateAuthorizationServerPolicyRule(ctx context.Context, authServerId string, policyId string, body AuthorizationServerPolicyRule)`

**Comment by mayitbeegh** [comment]
Thanks for the update

**Pull request closed without merging**
