### PR TITLE
Adding the reactivate API

### PR DESCRIPTION
**Pull request by thakurv**

### CODE REVIEW

**Comment by paulquerna-okta** [comment]
I think something went wrong with the vendor / Gopkg here -- its vendor'ed itself as a dependency

**Comment by thakurv** [comment]
This has been fixed now. Can you pls review

**Comment by ailsachiu** [comment]
Bump! I'd also like to use this so I don't have to move forward with a fork. :)

**Comment by bretterer** [comment]
Thank you for your PR here, however, this file is autogenerated from our OpenAPI spec as stated at https://github.com/okta/okta-sdk-golang/blob/31fd508a155972d890dfd828cb6286f5731a0ab8/okta/user.go#L17

We would need to update the spec internally to include this endpoint and then re-generate the library.

**Comment by bretterer** [comment]
This has been added in v2.0.0 of the SDK. Thank you for your contribution

**Pull request closed without merging**
