### PR TITLE
Fixes generated array types

### PR DESCRIPTION
**Pull request by andrewhamilton-okta**
Fixes issue #81 where the generator type selector to properly set the type of an array based stucts when it's a custom type and not a string.

### CODE REVIEW

**Comment by lwalter** [comment]
+1
I'm curious what the status is on the PR? The fix contained here unblocks features for user management and provisioning.

Thanks!

**Comment by broamski** [comment]
:wave: Is there an ETA on review for this?

**Comment by maxschae4** [comment]
Please?

**Comment by bretterer** [comment]
Taking a look at this today

**Comment by bretterer** [comment]
Closing and re-opening to try to force a travis build

**Pull request closed without merging**
