### PR TITLE
Readme fixes

### PR DESCRIPTION
**Pull request by thylong**
Hello,

You'll find 2 commits in the following PR, both are related to documentation update. Changelog:
- I added the missing contributing guide based on the Java one (it doesn't look like anything is going to change).
- Fixed the command you provide to install the SDK using Go

Have a good one 😊 

EDIT: I signed and sent the CLA by mail

### CODE REVIEW

**Comment by michaelw** [comment]
bump, can we get this merged, please?  I imagine the installation instructions is something that anybody using this for the first time is going to run into...

**Comment by nbarbettini** [comment]
@bretterer LGTM

**Comment by bretterer** [comment]
Will need to have this targeted again the `develop` branch before merging.

**Comment by bretterer** [comment]
Since this was branched off master and a rebase would need to be done, I am closing this PR but integrating these changes in a new branch.

Thank you for the contribution!

**Pull request closed without merging**
