### PR TITLE
Change Cache Ref to v2

### PR DESCRIPTION
**Pull request by ymylei**
Changed cache import in `config.go` to v2 sdk instead of v1 sdk.

Ran go mod tidy and go mod vendor.

Up testify to github.com/stretchr/testify v1.6.1

Made for #149

### CODE REVIEW

**Comment by ymylei** [comment]
@bretterer Could I get this looked at / reviewed by you or someone else on the maintainer team? The build fails because of https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions but I can provide my local test results.

**Comment by ymylei** [comment]
```
make test:unit
make[2]: Entering directory '/home/tom/okta-sdk-golang'
\x1b[0;32mRunning unit tests...\x1b[0m
go test ./tests/unit -test.v
=== RUN   Test_cache_key_can_be_created_from_request_object
--- PASS: Test_cache_key_can_be_created_from_request_object (0.00s)
=== RUN   Test_an_item_can_be_stored_in_cache
--- PASS: Test_an_item_can_be_stored_in_cache (0.00s)
=== RUN   Test_an_item_can_be_deleted_from_cache
--- PASS: Test_an_item_can_be_deleted_from_cache (0.00s)
=== RUN   Test_cache_can_be_cleared
--- PASS: Test_cache_can_be_cleared (0.00s)
=== RUN   Test_panic_on_empty_url
--- PASS: Test_panic_on_empty_url (0.00s)
=== RUN   Test_panic_when_url_contains_yourOktaDomain
--- PASS: Test_panic_when_url_contains_yourOktaDomain (0.00s)
=== RUN   Test_panic_when_url_contains_admin_okta_com
--- PASS: Test_panic_when_url_contains_admin_okta_com (0.00s)
=== RUN   Test_panic_when_url_contains_admin_oktapreview_com
--- PASS: Test_panic_when_url_contains_admin_oktapreview_com (0.00s)
=== RUN   Test_panic_when_url_contains_admin_okta_emea_com
--- PASS: Test_panic_when_url_contains_admin_okta_emea_com (0.00s)
=== RUN   Test_panic_when_url_contains_com_com
--- PASS: Test_panic_when_url_contains_com_com (0.00s)
=== RUN   Test_panic_when_url_does_not_begin_with_https
--- PASS: Test_panic_when_url_does_not_begin_with_https (0.00s)
=== RUN   Test_panic_when_api_token_is_empty
--- PASS: Test_panic_when_api_token_is_empty (0.00s)
=== RUN   Test_panic_when_api_token_contains_placeholder
--- PASS: Test_panic_when_api_token_contains_placeholder (0.00s)
=== RUN   Test_panic_when_authorization_mode_is_not_valid
--- PASS: Test_panic_when_authorization_mode_is_not_valid (0.00s)
=== RUN   Test_does_not_panic_when_authorization_mode_is_valid
--- PASS: Test_does_not_panic_when_authorization_mode_is_valid (0.00s)
=== RUN   Test_will_panic_if_private_key_authorization_type_with_missing_properties
--- PASS: Test_will_panic_if_private_key_authorization_type_with_missing_properties (0.00s)
=== RUN   Test_429_Will_Automatically_Retry
--- PASS: Test_429_Will_Automatically_Retry (2.00s)
=== RUN   Test_Will_Stop_Retrying_Based_On_Max_Retry_Configuration
--- PASS: Test_Will_Stop_Retrying_Based_On_Max_Retry_Configuration (2.00s)
=== RUN   Test_Will_Handle_Backoff_Strategy_For_429
--- PASS: Test_Will_Handle_Backoff_Strategy_For_429 (2.00s)
=== RUN   Test_a_429_with_x_reset_header_throws_error
--- PASS: Test_a_429_with_x_reset_header_throws_error (0.00s)
=== RUN   Test_a_429_with_no_date_header_throws_error
--- PASS: Test_a_429_with_no_date_header_throws_error (0.00s)
=== RUN   Test_gets_the_correct_backoff_time
--- PASS: Test_gets_the_correct_backoff_time (0.00s)
=== RUN   Test_with_multiple_x_rate_limit_request_times_still_retries
--- PASS: Test_with_multiple_x_rate_limit_request_times_still_retries (0.00s)
=== RUN   Test_Create_Session
--- PASS: Test_Create_Session (0.00s)
PASS
ok      github.com/okta/okta-sdk-golang/v2/tests/unit   6.006s
```

**Comment by bretterer** [comment]
Looking into this Today.  Thank you for your PR!

**Comment by bretterer** [comment]
It seems there are more updates here than just the cache. Can you explain what else had changed and why?  Looks like a lot of vendor files

**Comment by ymylei** [comment]
@bretterer 
My apologies for not making it super clear, so I've done the following:
1. Fix the cache reference so it's going to V2
2. Use `go mod` to update the version of testify used to `1.6.1` from `1.5.1`
3. I also ran `go mod tidy` and `go mod vendor` on the dir after the ^, this was so the full cleanup of the deps occurred since we were pulling in the v1 of the okta sdk, which also included all of it's deps. 

If there are any of these changes you'd like me to revert on this PR let me know and I'll do so ASAP.

**Review by bretterer — APPROVED** [review]

**Pull request closed without merging**
