### PR TITLE
Fix WithPrivateKey option handling of long strings

### PR DESCRIPTION
**Pull request by adw1n**
Relates to https://github.com/okta/okta-sdk-golang/issues/206

@bogdanprodan-okta @bretterer I'd very much appreciate review on this one. It probably doesn't fix the whole error handling but it's a start which at least unblocks me.

### CODE REVIEW

**Comment by bretterer** [comment]
Hi @adw1n. Thanks for the PR.  Does this do the same as #207 where this would not be needed when we merge in #207?

**Comment by adw1n** [comment]
@bretterer https://github.com/okta/okta-sdk-golang/pull/207 takes the approach of blindly ignoring errors which I'm not a fan of. It makes debugging certain kind of errors next to impossible. I can't pull any examples from the top of my head but think of what would happen when a syscall returns `interrupted system call`, `cannot allocate memory`, `interrupted system call`, `operation not permitted`, `device or resource busy` and how that should be handled.

**Comment by bogdanprodan-okta** [comment]
@adw1n let's handle all the errors, but just add some warn log or message into the code, so the user will understand what's happening

**Comment by adw1n** [comment]
Closing this since maintainers decided to go with https://github.com/okta/okta-sdk-golang/pull/207

**Comment by adw1n** [comment]
@bogdanprodan-okta you have to be really careful with any sort of logging here. The error might contain the `filename` which might not be a filename at all - it might be a private key. You most definitely don't want to log a private key. I think this function should return false on errors that we expect and panic on unexpected errors. I also think there must be a better solution than passing a private key as filename.

**Pull request closed without merging**
